version: "3.9"

networks:
  iced-latte-network:
    name: iced-latte-network
    attachable: true

services:
  iced-latte-frontend:
    image: 'zufarexplainedit/iced-latte-frontend:${DOCKER_IMAGE_TAG}'
    container_name: latte-frontend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - iced-latte-network
