name: Dev PR Build and Test Pipeline

on:
  pull_request:
    branches:
      - development

jobs:
  sonarqube:
    name: Tests and SonarQube
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install --development

      - name: Linter
        run: npm run lint

      - name: Build (checks validity of types etc.)
        run: npm run build

      - name: Test and Coverage
        run: npm run test --coverage

      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectVersion=pr-${{ github.event.pull_request.number }}
        env:
          SONAR_TOKEN: sqp_d5037397d43452eb548ffb026abd6ecccbfce756
          SONAR_HOST_URL: http://31.132.209.218:63535

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
           SONAR_TOKEN: sqp_d5037397d43452eb548ffb026abd6ecccbfce756
           SONAR_HOST_URL: http://31.132.209.218:63535
